include $(APPDIR)/Make.defs
PROGNAME  = velacare
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_438_VELACARE)
MAINSRC = velacare_main.c
CSRCS  = velacare_state.c velacare_sensor.c velacare_skill.c velacare_lvgl.c velacare_tts.c velacare_cron.c
include $(APPDIR)/Application.mk
